Fixed #18192 -- Allow IO errors to raise with missing translation files.
Otherwise fails downstream at `res._info.copy()` with:
 > AttributeError: 'NoneType' object has no attribute '_info'

An ambiguous error that does not expose the real issue.

Related:
https://code.djangoproject.com/ticket/18192
https://groups.google.com/forum/#!msg/django-users/tc0asF6iFBo/u3cBN0SlUl0J

Remove line of code that can never execute:
`if res is None` since same `AttributeError` will first raise.